### ISSUE TITLE
Teleport (Commandblock/Enderpearl) = Cheat

### ISSUE THREAD

**Issue by textilkleber1** [n33d4n4m3/NoCheatMinus#16]

**Comment by n33d4n4m3** [comment]
I can confirm that. Certain checks like MissingBlock, MissingEntity, or even Distance are unfortunately not tweakable in their final form because their function is based on pure Minecraft game mechanics that cannot be changed from Vanilla. It is possible to make minor adjustments, such as detecting if an Enderpearl was nearby during the check less than five seconds ago. This would possibly solve the problem, but it opens up new ones. For example, this would be a vulnerability for a bypass in a cheat. The CMD block/command teleport problem is almost impossible to solve. The server admin who installed NCM on the server would have to make the check suspend just before an upcoming teleport and resume after the teleport completes. Spontaneous and unplanned teleport operations by players (the /teleport command) cannot be detected and therefore do not pass the distance check.

All in all this is not so bad because MissingBlock, MissingEntity and Distance are planned as threshold checks. I have planned several punishment functions for players (Banwaves and Ragecheat-Cancelling). These punishment functions will wait until multiple fails of these threshold checks accumulate. Only then a punishment will follow, just to make sure that not a single false positive (like e.g. teleport) will lead to a punishment.
This means that it's already taken into account that this check can be failed several times without using cheats.
